from typing import TypedDict


class AgentState(TypedDict):
    """Shared state schema for the research agent graph.

    Passed between nodes in the LangGraph workflow to carry
    inputs, intermediate tool results, and the final response.
    """

    query: str
    """User's input query."""

    web_search_result: str
    """Raw result returned by the web search tool."""

    arxiv_result: str
    """Raw result returned by the ArXiv search tool."""

    response: str
    """Final synthesized response generated by the agent."""